version: '3'

services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - my_bridge_network
    depends_on:
      mysql_db:
        condition: service_healthy

  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: prepit_test
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_BIND_ADDRESS: 0.0.0.0
    networks:
      - my_bridge_network
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  my_bridge_network:
    driver: bridge

volumes:
  mysql_data: